default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  username: blog_admin
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: blog_dev
  host: localhost
  password: 'postgres'

test:
  <<: *default
  database: blog_test
  host: localhost
  password: 'postgres'

production:
  <<: *default
  database: blog_prod
