default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  username: blog_admin
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: blog_dev
  host: localhost

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_prod
